### ISSUE TITLE
google-services.json

### ISSUE THREAD

**Issue by domgjntoki** [coma-na-ufba/android-app#1]
Acho q n é uma boa ideia deixar o ``google-services.json`` assim pros outros verem com as id e tal

**Comment by pablohildo** [comment]
Opa, tranquilo, @domgjntoki ? =)
No geral realmente não é, mas a ideia quando subi o repo é que todo mundo possa rodar sem precisar realizar nenhum procedimento. Além disso, no pior dos casos o limite de requisições seriam atingidos, já que todos os serviços estão limpos e não existe nenhum dado importante nem billing info. 
Nesse momento, por outro lado, a maioria dos serviços já foram desabilitados também. Mas agradeço a preocupação!
Abçs =)
